### ISSUE TITLE
No messages reported because visit_callfunc is never called

### ISSUE THREAD

**Issue by RevolutionTech** [davidszotten/sentry-stack-checker#1]
This checker fails to report any messages since `visit_callfunc()` is never called.

Fortunately, the checker seems to work if `visit_callfunc` is renamed to `visit_call`.

I am running `pylint` on Python 2.7.11 with `astroid==1.6.1` and `pylint==1.8.2`. My guess is that somewhere along the line `visit_callfunc` was renamed to `visit_call`, but I am having trouble finding exactly where this happened.

**Comment by davidszotten** [comment]
thanks!
