### ISSUE TITLE
sentry_stack_checker is not on PyPi

### ISSUE THREAD

**Issue by RevolutionTech** [davidszotten/sentry-stack-checker#3]
The installation instructions in the `README` say:
```shell
$ pip install sentry_stack_checker
```
but this will fail because `sentry_stack_checker` is not on PyPi.

If you don't want to upload the project to PyPi, you could update this line to suggest installing it via Github:
```shell
$ pip install git+ssh://git@github.com/davidszotten/sentry-stack-checker.git
```

###### Also, thank you so much for taking a look at my other two issues. This is the last one I have for now- promise!

**Comment by davidszotten** [comment]
it is on pypi as of 25 minutes ago
