### ISSUE TITLE
Ability to configure logging levels that add messages

### ISSUE THREAD

**Issue by RevolutionTech** [davidszotten/sentry-stack-checker#4]
My team has been using this checker for a little while now, but we've had to disable it because this checker adds messages for info and debug logs, and on our team we do not send info or debug logs to Sentry so we do not want to record the stack trace for any of those logs.

I realize that this is may be specific to our team, but I am wondering if you agree with me that perhaps the logging levels that this checker adds messages to should be configurable.

Happy to work on a PR for this if you agree that it would be useful but don't have time to work on it.

###### P.S. I know I promised I wouldn't open another issue for a while and it hasn't been that long since my last one, so I am sorry about that.

**Comment by davidszotten** [comment]
how does configuration of pylint plugins work?

**Comment by RevolutionTech** [comment]
Options for a checker are briefly described here:
https://docs.pylint.org/en/1.8/how_tos/custom_checkers.html

> The options list defines any user configurable options. It has the following format:
```
options = (
    'option-symbol': {'argparse-like-kwarg': 'value'},
)
```
> The `option-symbol` is a unique name for the option. This is used on the command line and in config files. The hyphen is replaced by an underscore when used in the checker, similarly to how you would use `argparse.Namespace`.

Two ideas for toggling different loggers: a boolean option for _each_ separate logger, ie.
```python
options = (
    (
        'report-debug',
        {
            'default': True, 'type': 'yn', 'metavar' : '<y_or_n>',
            'help': 'Report messages for debug logs',
        }
    ),
    (
        'report-info',
        {
            'default': True, 'type': 'yn', 'metavar' : '<y_or_n>',
            'help': 'Report messages for info logs',
        }
    ),
    (
        'report-warning',
        {
            'default': True, 'type': 'yn', 'metavar' : '<y_or_n>',
            'help': 'Report messages for warning logs',
        }
    ),
    ...
)
```
or one option that contains a comma-separated list of the loggers that should be reported, ie.
```python
options = (
    (
        'report-loggers',
        {
            'default': 'debug,info,warning,error', 'type': 'csv', 'metavar' : '<logging methods>',
            'help': 'List of logging methods that should generate messages',
        }
    ),
)
```

**Comment by davidszotten** [comment]
nice. i think my preference is your second idea, a single option, to not pollute the option namespace too much.
